### ISSUE TITLE
The specified resource type cannot be found in the image file.

### ISSUE THREAD

**Issue by tiansin** [rodrigocfd/windigo#10]
If compiled as a dynamic link library, icon assets cannot be loaded.

**Comment by rodrigocfd** [comment]
How are you embedding tthe icons?

**Comment by tiansin** [comment]
> How are you embedding tthe icons?

> minimal.syso

**Comment by tiansin** [comment]
I think the problem is getting the instance handle.

**Comment by rodrigocfd** [comment]
Let me see the code you're using.

**Comment by rodrigocfd** [comment]
Closed after 4 months of abandonment.
