### ISSUE TITLE
[Feature] DDE support/bindings

### ISSUE THREAD

**Issue by ghost** [rodrigocfd/windigo#13]
DDE (dynamic data exchange, [DDE docs](https://docs.microsoft.com/en-us/windows/win32/dataxchg/about-dynamic-data-exchange)) is used widely in Windows and it'd be great if there were a way to create (at least) DDE clients and (possibly) DDE servers in Go using windigo.

**Comment by rodrigocfd** [comment]
Oh yes, I remember using DDE a long time ago. [Are these](https://docs.microsoft.com/en-us/windows/win32/dataxchg/dynamic-data-exchange-functions) the APIs you need?

**Comment by AfricanElephant** [comment]
> Oh yes, I remember using DDE a long time ago. [Are these](https://docs.microsoft.com/en-us/windows/win32/dataxchg/dynamic-data-exchange-functions) the APIs you need?

Sorry, I should've been more specific. [These are](https://docs.microsoft.com/en-us/windows/win32/api/ddeml/) APIs I'm looking to use in my project, the ddeml.h header.

**Comment by rodrigocfd** [comment]
I've committed the first calls. I believe the API is clean enough:

```go
hdde, err := win.DdeInitialize(
	func(wType co.XTYP, wFmt uint32, hConv win.HCONV,
		hsz1, hsz2 win.HSZ, hData, dwData1, dwData2 uintptr) uintptr {
		return 0
	},
	co.AFCMD_APPCLASS_STANDARD,
)
if err != nil {
	panic(err)
}
defer hdde.DdeUninitialize()

ss := hdde.DdeCreateStringHandle("Hello")
defer hdde.DdeFreeStringHandle(ss)
println(hdde.DdeQueryString(ss))

println("DONE")
```

Please let me know if they work for you.

**Comment by rodrigocfd** [comment]
I just commited the [`DdeClientTransaction`](https://github.com/rodrigocfd/windigo/blob/master/win/user_hdde.go#L152) and [`DdeFreeDataHandle`](https://github.com/rodrigocfd/windigo/blob/master/win/user_hdde.go#L185), but I really have no idea how to test them.

Can you check if are they OK?

**Comment by jaevor** [comment]
```py

**Comment by jaevor** [comment]
This Python code creates a DDE server named `py_dde_server` and it has one topic `my_topic` which has one item `my_item`, that is the current time.
```py
import time
import win32ui, dde
from pywin.mfc import object


class DDETopic(object.Object):
    def __init__(self, topicName):
        self.topic = dde.CreateTopic(topicName)
        object.Object.__init__(self, self.topic)
        self.items = {}

    def setData(self, itemName, value):
        try:
            self.items[itemName].SetData( str(value) )
        except KeyError:
            if itemName not in self.items:
                self.items[itemName] = dde.CreateStringItem(itemName)
                self.topic.AddItem( self.items[itemName] )
                self.items[itemName].SetData( str(value) )


server = dde.CreateServer()
server.Create("python_dde_sever")
ddeTopic = DDETopic("my_topic")
server.AddTopic(ddeTopic)

while True:
    current_time = time.time() # is a number like, 1656394098.8112526
    ddeTopic.setData("my_item", current_time)
    win32ui.PumpWaitingMessages(0, -1)
    time.sleep(0.5)
```

Attempting to query the server with this Go code,
```go
package main

import (
	"log"

	"github.com/rodrigocfd/windigo/win"
	"github.com/rodrigocfd/windigo/win/co"
)

func main() {
	hdde, err := win.DdeInitialize(
		func(wType co.XTYP, wFmt uint32, hConv win.HCONV,
			hsz1, hsz2 win.HSZ, hData, dwData1, dwData2 uintptr) uintptr {
			return 0
		},
		co.AFCMD_APPCLASS_STANDARD,
	)

	if err != nil {
		panic(err)
	}

	defer hdde.DdeUninitialize()

	name := win.StrOptSome("py_dde_server")
	topic := win.StrOptSome("my_topic")
	item := win.StrOptSome("my_item")

	// *Error is returned*
	hconv, err := hdde.DdeConnect(name, topic, nil)

	defer hdde.DdeDisconnect(hconv)

	if err != nil {
		panic(err)
	}

	var data []byte

	// 0x1030 = XTYP_ADVSTART
	k, err := hdde.DdeClientTransaction(data, hconv, item, 0, 0x1030, 10)
	if err != nil {
		panic(err)
	}

	log.Println(k)
	log.Println(data)
}
```
Results in an error; 
```
panic: [16394 0x400a]

goroutine 1 [running]:
main.main()
        C:/Users/Jaden/Desktop/dde/cmd/main.go:34 +0x225
exit status 2
```
Hopefully it is easier to test with the python -- since it is like the only programming language other than C(++) that has it in its lib. DDE feels so legacy lol.

**Comment by rodrigocfd** [comment]
As far as I could grasp from the documentation, when calling [`DdeConnect`](https://docs.microsoft.com/en-us/windows/win32/api/ddeml/nf-ddeml-ddeconnect), you must pass the name of an **existing** service to connect to. Or, don't pass any name at all to connect to any available server.

So, the code below connects without errors:

```go
func main() {
	hDde, err := win.DdeInitialize(func(
		wType co.XTYP, wFmt uint32, hConv win.HCONV,
		hsz1, hsz2 win.HSZ, hData, dwData1, dwData2 uintptr) uintptr {
		return 0
	}, co.AFCMD_APPCLASS_STANDARD)
	if err != nil {
		panic(err)
	}
	defer hDde.DdeUninitialize()

	hConv, err := hDde.DdeConnect(win.StrOptNone(), win.StrOptNone(), nil)
	if err != nil {
		panic(err)
	}
	defer hDde.DdeDisconnect(hConv)

	hData, err := hDde.DdeClientTransaction(
		nil, hConv, win.StrOptNone(), co.CF_TEXT, co.XTYP_ADVSTART, 10)
	if err != nil {
		panic(err)
	}
	defer hDde.DdeFreeDataHandle(hData)
}
```

However, `DdeClientTransaction` is returning `INVALIDPARAMETER`, so now it seems it's just a matter of passing the correct parameters.

Please let me know if it's working now.

**Comment by rodrigocfd** [comment]
@AfricanElephant What's the Python code you're using to query the DDE service?

**Comment by rodrigocfd** [comment]
Where can I find the source code of this Python library? This library is completely different from all native APIs, its author created a whole different abstraction over it. I'll have to dig into the source code to see what APIs are being actually called.

**Comment by rodrigocfd** [comment]
I still don't know exactly what you need, but I found [this C++ example](https://github.com/JohnGreenan/AlignmentDDE/blob/master/AlignmentDDE/main.cpp), which looks pretty close.

All the needed functions are implemented, is this what you need?
