### ISSUE TITLE
MapViewOfFile fails when arch is 386

### ISSUE THREAD

**Issue by Hoto-Cocoa** [rodrigocfd/windigo#24]
When I used `win.IniLoad`, It fails with error: `[5 0x05] Access is denied.`, but not with amd64.

I tried to fix this issue but failed.

How can I fix this? INI file size is just 1,536 bytes.

Thanks.

**Comment by rodrigocfd** [comment]
I made two commits to stricten the behavior of MapViewOfFile, but I'm unsure it would make any difference in x86 architectures. The behavior of the C implementation is the same for any architecture.

What's the latest Windows to support x86? I can try downloading an ISO and installing it in a VirtualBox machine to test.

**Comment by rodrigocfd** [comment]
The pkg.dev may take some time to deploy the documentation, but the code is already commited. You can use it right away.

**Comment by Hoto-Cocoa** [comment]
Thanks for let me know, I just tried update and got new version.

However, now `[87 0x57] The parameter is incorrect.` error occurred.

**Comment by rodrigocfd** [comment]
This error is coming from which function call?

**Comment by Hoto-Cocoa** [comment]
Now `WriteFile: %!w(<nil>)` error occurred. It seems to changes in c71c216 caused make `err != nil` always true.

However, the file saved successfully.

**Comment by rodrigocfd** [comment]
I missed an error check, please try again.

**Comment by Hoto-Cocoa** [comment]
It now works perfectly! Thanks a lot for the support.
