### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by mk360** [rodrigocfd/windigo#34]
Is there any documentation to use the library? I tried running the example and it worked (although...), and I'd like to build on top of it. But I can't seem to find any documentation anywhere. For example, I wanted to make my window draggable, but can't find out how to do that 😅 

Also, is there a way to catch runtime errors (in the console for example)? The window seems to freeze after just one interaction.

**Comment by rodrigocfd** [comment]
> Is there any documentation to use the library? I tried running the example and it worked (although...), and I'd like to build on top of it. But I can't seem to find any documentation anywhere. For example, I wanted to make my window draggable, but can't find out how to do that

It's a layer over the Win32 API, so just follow the documentation of the Win32 functions you're calling.

> Also, is there a way to catch runtime errors (in the console for example)? The window seems to freeze after just one interaction.

You'll have to [catch each error](https://go.dev/blog/error-handling-and-go) that interests you.
