### ISSUE TITLE
 VerSetConditionMask 32-bit system parameter error

### ISSUE THREAD

**Issue by tiansin** [rodrigocfd/windigo#8]
Running in 32 programs will crash. Because in 32 programs 'ULONGLONG' is passed with two parameters.

https://github.com/vito/houdini/blob/d5a6d80a3b87f479919ab5c6bc4badd4de80f57e/win32/win32_windows_amd64.go#L15
https://github.com/vito/houdini/blob/d5a6d80a3b87f479919ab5c6bc4badd4de80f57e/win32/win32_windows_386.go#L24

**Comment by rodrigocfd** [comment]
Currently I can only test it on x64, so for x32 I'm following the implementation you gave me. If it doesn't work, please open another issue.
