### ISSUE TITLE
GetWindowLongPtrW&SetWindowLongPtrW Not found.

### ISSUE THREAD

**Issue by tiansin** [rodrigocfd/windigo#9]
Failed to find GetWindowLongPtrW procedure in user32.dll: The specified procedure could not be found.
Failed to find SetWindowLongPtrW procedure in user32.dll: The specified procedure could not be found.

**Comment by tiansin** [comment]
Can it be?

> GetWindowLongW & SetWindowLongW

**Comment by rodrigocfd** [comment]
> Can it be?
> 
> > GetWindowLongW & SetWindowLongW

Yes, in 32-bit environments. I'll add them.
